create table cart_product
(
    cart_id    integer not null,
    product_id integer not null,
    primary key (cart_id, product_id)
);
create table carts
(
    id          integer generated by default as identity,
    description varchar(255),
    summa       numeric(19, 2),
    person_id   integer,
    primary key (id)
);
create table persons
(
    id         integer generated by default as identity,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    username   varchar(255) not null,
    primary key (id)
);
create table roles (
    id integer not null,
    name varchar(255),
    primary key (id)
);
create table person_role (
    person_id integer not null,
    role_id integer not null,
    primary key (person_id, role_id)
);
create table products
(
    id      integer generated by default as identity,
    name    varchar(255),
    price   numeric(19, 2),
    shop_id integer,
    primary key (id)
);
create table shop_person
(
    shop_id   integer not null,
    person_id integer not null,
    primary key (shop_id, person_id)
);
create table shops
(
    id           integer generated by default as identity,
    name         varchar(255),
    phone_number varchar(255),
    web_site     varchar(255),
    primary key (id)
);
alter table cart_product
    add constraint FKreo7xwp4sy8mglrlf0b6hkr3e
        foreign key (product_id)
            references products;
alter table cart_product
    add constraint FK8bhydybldutgf7a82oxkctlgs
        foreign key (cart_id)
            references carts;
alter table carts
    add constraint FKn7i4384wn1xk85949e3a6fjwv
        foreign key (person_id)
            references persons;
alter table products
    add constraint FK7kp8sbhxboponhx3lxqtmkcoj
        foreign key (shop_id)
            references shops;
alter table shop_person
    add constraint FK5nn2ixhcd49rpp4itge8677pc
        foreign key (person_id)
            references persons;
alter table shop_person
    add constraint FK90f3f6415fm67f2cc64hj1ue7
        foreign key (shop_id)
            references shops;
alter table persons
    add constraint UK_e1ncq4llddwrkjddsvxp41prh unique (username);
alter table person_role
    add constraint FK1hakvwv4tnv13s8ywg4n90vyj
        foreign key (role_id)
            references roles;
alter table person_role
    add constraint FKns0nvce04i8llrl8sgs5lpfas
        foreign key (person_id)
            references persons;

insert into roles (id, name) values (1, 'ROLE_ADMIN');
insert into roles (id, name) values (2, 'ROLE_CUSTOMER');

insert into shops (name, phone_number, web_site)
values ('Shop-1', '123-456-789', 'shop1.com.ua');
insert into shops (name, phone_number, web_site)
values ('Shop-2', '234-567-890', 'shop2.com.ua');
insert into shops (name, phone_number, web_site)
values ('Shop-3', '345-678-901', 'shop3.com.ua');

insert into persons (email, first_name, last_name, username, password)
values ('admin@domain', 'admin', 'admin', 'admin', '$2a$10$heABL60k2oCrO07H0AowwuWvJQf2wf3ShKLNgle/oHyRgImflZ18O');
insert into persons (email, first_name, last_name, username, password)
values ('first2.last2@domain', 'Petr', 'Petrov', 'petrov', '$2a$10$heABL60k2oCrO07H0AowwuWvJQf2wf3ShKLNgle/oHyRgImflZ18O');
insert into persons (email, first_name, last_name, username, password)
values ('first3.last3@domain', 'Vasya', 'Pupkin', 'pupkin', '$2a$10$heABL60k2oCrO07H0AowwuWvJQf2wf3ShKLNgle/oHyRgImflZ18O');

insert into person_role (person_id, role_id)
values (1, 1);
insert into person_role (person_id, role_id)
values (2, 2);
insert into person_role (person_id, role_id)
values (3, 2);

insert into products (name, price)
values ('Printer HP', '170.00');
insert into products (name, price)
values ('Printer Epson', '165.00');
insert into products (name, price)
values ('Mouse Genius', '17.00');
insert into products (name, price)
values ('Router Asus', '300.00');
insert into products (name, price)
values ('Monitor Samsung', '200.00');
insert into products (name, price)
values ('Processor Intel i9', '1200.00');



